server:
  port: 8081 # Puerto donde corre el servicio

spring:
  application:
    name: usuarios-servicio # Nombre del microservicio

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL del Eureka Server
    register-with-eureka: true # Habilita el registro
    fetch-registry: true       # Obtiene registros de otros servicios
