version: '3.9'

services:
  mongodb:
    image: mongo:5.0 # Imagen oficial de MongoDB
    container_name: mongodb
    ports:
      - "27017:27017" # Exposición del puerto predeterminado de MongoDB
    volumes:
      - mongodb_data:/data/db # Persistencia de datos
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mi_red

  mongo_express:
    image: mongo-express:latest # Herramienta visual para gestionar MongoDB
    container_name: mongo_express
    ports:
      - "8081:8081" # Puerto para acceder a la interfaz de Mongo Express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - mi_red

  backend:
    build:
      context: ./backend # Directorio donde está el Dockerfile del backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/mi_base_datos
    depends_on:
      - mongodb
    networks:
      - mi_red

volumes:
  mongodb_data: # Volumen para almacenar los datos de MongoDB

networks:
  mi_red: # Red privada para comunicación entre los servicios
